- name: List Installed Packages
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Install Nmap
      apt:
        name: nmap
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Add root to docker group
      user:
        name: root
        groups: docker
        append: yes
