- name: List Installed Packages
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Print the ansible_user variable
      debug:
        var: ansible_user

    - name: Install Nmap
      apt:
        name: nmap
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present
