- name: List Installed Packages
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Install Nmap
      apt:
        name: nmap
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Install Docker Engine
      apt:
        name: docker.io
        state: present

    - name: Add user to docker group
      group:
        name: docker
        ensure: present
        members: "{{ ansible_user }}"
