- name: List Installed Packages
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Create a file with package list
      file:
        path: /tmp/package_list.txt
        state: touch
        content: "{{ ansible_facts.packages }}"
