- name: apt update and upgrade Debian packages
  hosts: all
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600 # 1 hour
